name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  http: ^1.1.0
  dio: ^5.3.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  file_selector: ^0.9.0
  intl: ^0.18.1
  flutter_svg: ^1.0.0
  url_launcher: ^6.2.1
  share_plus: ^9.0.0
  provider: ^6.0.5
  open_filex: ^4.3.4
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
